version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - frontend

volumes:
  node_modules:
