version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - utopia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - frontend
    networks:
      - utopia-network

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - utopia-network

networks:
  utopia-network:
    driver: bridge

volumes:
  node_modules:
  db_data:
